### ISSUE TITLE
建议：添加每次上线时手动选择某次提交或分支功能？

### ISSUE THREAD

**Issue by walkonthemarz** [dreamans/syncd#10]
现在不希望在项目配置时直接写死上线的分支或tag，希望每次提交上线单时能够手动选择某次git提交或分支，便于灵活上线

**Comment by dreamans** [comment]
这种开发规范不太推荐，会导致线上代码比较混乱，推荐的做法：
1. tag方式里程碑式上线，能控制迭代节奏；
2. 指定分支(比如master)分支上线，小步快跑快速迭代集成；
