### ISSUE TITLE
syncd是否支持优雅关闭

### ISSUE THREAD

**Issue by violetgo** [dreamans/syncd#11]
syncd是否支持优雅关闭？在发布节点的时候是否能做到业务上不感知？

**Comment by dreamans** [comment]
"在发布节点的时候是否能做到业务上不感知？" 这个单纯靠部署不好解决，应该依赖具体项目的高可用方案

**Comment by violetgo** [comment]
也就是说节点的移除事件需要在项目的注册中心中自己实现，syncd负责将kill信号传递给业务组件，然后业务自己来处理释放优雅停止的逻辑是么？

那关于自动回归呢？比如如何来快速的验证上线的节点是否可用，比如是否成功率会比其他的节点低等因素是否有考虑？

**Comment by dreamans** [comment]
#### 也就是说节点的移除事件需要在项目的注册中心中自己实现?

回答：

我感觉这个问题更应该是系统架构层面需要考虑的，单纯的靠部署系统不太好解决，syncd的上线流程如下:
```
执行`pre-deploy` (可停掉服务)  --> 部署安装包 --> 执行`post-deploy`  (重启服务)
```
不过可以写自定义脚本，在pre-deploy阶段调用，通知 etcd/consul从服务列表中摘掉，待post-deploy阶段再通知进行节点恢复（这样虽然烦琐，但对业务系统无侵入性）。

#### syncd负责将kill信号传递给业务组件，然后业务自己来处理释放优雅停止的逻辑是么？

不太明白这句话。

#### 那关于自动回归呢？

这个目前没有在生产环境支持的计划

#### 比如如何来快速的验证上线的节点是否可用，比如是否成功率会比其他的节点低等因素是否有考虑？

有更专业的监控系统来做这些事，syncd就不进行扩展了，如果只想简单的验证下服务是否正常，可以在post-deploy阶段自定义脚本实现。
