### ISSUE TITLE
maven 构建异常时不打印异常信息

### ISSUE THREAD

**Issue by 1032924429** [dreamans/syncd#119]
java maven项目构建脚本：mvn clean install package -DskipTests -Pdev
如果构建失败了，仅显示执行失败，但是没有显示失败的具体信息。导致失败了也还是要去服务器上构建来查看原因

**Comment by dreamans** [comment]
可以在构建脚本中将错误信息重定向到标准错误中试试。

**Comment by 1032924429** [comment]
> 可以在构建脚本中将错误信息重定向到标准错误中试试。

thanks, 我了解你的思路，但期望有更好的支持。
------------------
特征：
syncd在异常时仅显示标准错误输出，在成功时仅显示标准输出。
-----------------
问题：
打包命令执行失败时，打包命令的异常信息仍然是标准输出，如果都转换为错误输出，打包成功时，我发现syncd不显示异常输出，导致无输出。于是我会将打包命令的输出重定向到临时文件中，从临时文件中读取2次，一次到标准输出，一次到标准错误输出，这样成功失败都会有信息输出

期待：
不管脚本执行成功还是失败，把标准输出和标准错误输出都显示出来，可以做到么
