### ISSUE TITLE
加入sqlite pg的支持吧

### ISSUE THREAD

**Issue by inspurhua** [dreamans/syncd#19]

**Comment by dulumao** [comment]
说真的，能增加一些其他的驱动更好些，最好是内置一个DB，比如sqlite,比如我之前常用的金克斯，作为一个部署主机，真的没时间放在环境配置上，说实在的连编译mysql,都懒得弄，yum或者apt就算了,部署机器，非特殊情况我们也不会去看他的历史信息，有需要能找到就行，sqlite还是不错的选择,只要可以持久就行，到时候用一个通用的壳能访问到数据或者下载数据文件就足够了

**Comment by dreamans** [comment]
抱歉，目前没有支持其他数据库的计划。
