### ISSUE TITLE
填写上线申请单，拉取版本列表报错

### ISSUE THREAD

**Issue by xuanye** [dreamans/syncd#2]
{"code":1007,"message":"fatal: unknown date format format:%Y-%m-%d %H:%M:%S\n"}

**Comment by dreamans** [comment]
请提供操作系统信息

**Comment by xuanye** [comment]
centos 7 64bit

**Comment by eagle-1949** [comment]
我的也是啊
![image](https://user-images.githubusercontent.com/8033615/51160529-4d8ba000-18c9-11e9-84b7-65d7967a0a8c.png)
