### ISSUE TITLE
Add a url prefix for nginx reverse proxy

### ISSUE THREAD

**Issue by colben** [dreamans/syncd#20]
**Environment**: CentOS7.5 Nginx1.12.2 Syncd1.0.1
**Issue**: "location / {}" in my nginx is used by another application, so is there any way to add a url prefix(like "/syncd/") to static and api like this:
http://server/syncd/static
http://server/syncd/api

**Comment by dreamans** [comment]
Why not create a new "server {  }" config segment for syncd  :question:
