### ISSUE TITLE
如何使用构建

### ISSUE THREAD

**Issue by MicyToy** [dreamans/syncd#28]
我按照文档搭建了环境，但是没看到提到的构建环节。
目前项目是maven项目，不知道如何构建？

**Comment by yangkghjh** [comment]
也没找到

**Comment by cendechen** [comment]
没有找到构建脚本

**Comment by CaiHeLiu** [comment]
@MicyToy @yangkghjh @cendechen 

文档地址： https://rsy.me/syncd/#/install

**Comment by dreamans** [comment]
请参考文档：https://rsy.me/syncd/2.0/#/build
