### ISSUE TITLE
有个小需求能否实现?

### ISSUE THREAD

**Issue by station19** [dreamans/syncd#42]
机器多保证服务的时候 肯定是如下操作
①分批下线机器,然后代码推送到下线的机器上,再启动服务跑代码
②再上线刚刚下线的机器,以此类推...

希望楼主把需求加上去,否则只能在测试环境玩了...

**Comment by dreamans** [comment]
> 分批下线机器

我理解把机器从服务发现列表中摘掉吧，这个不是syncd考虑的范围，syncd可以开放更多的hook，在上线的各个阶段执行你自定义的动作，自定义动作负责上下线服务。
