### ISSUE TITLE
Feature request: 增加 Git 密钥, 拉取代码或者获取其他 Git 信息时使用

### ISSUE THREAD

**Issue by lostsnow** [dreamans/syncd#43]
现在应该是只支持使用 http(s) 的方式吧?

**Comment by dreamans** [comment]
支持git方式拉取代码，需要配置秘钥到git服务器.

see https://help.github.com/en/articles/connecting-to-github-with-ssh

**Comment by lostsnow** [comment]
恩 我想说的是手动指定私钥 不过用当前用户默认的私钥倒是也可以

**Comment by dreamans** [comment]
目前先保持现状吧
