### ISSUE TITLE
对syncd的一些建议

### ISSUE THREAD

**Issue by Succy** [dreamans/syncd#45]
### 在使用了一下syncd1.x版本之后，想对未来的版本写一些建议，其中有些也跟作者讨论了一下。

+ 建议增加发布回滚功能，并且保留的项目版本可以由用户自定义。
+ 建议除了排除某些不上线的文件外，支持只允许某些文件上线。
+ 建议增加构建钩子，可选性质(web前端项目可以不构建，npm + webpack的也可以构建， Jq类可不构建)，在beforeDepoly钩子前可选执行。
+ 建议增加项目启动/停止/重启等功能按钮和Hook钩子，其执行逻辑可以由用户使用python/shell等脚本实现，和afterDepoly Hook区分。（个人认为部署是由dep --> target server的过程，其他逻辑单元应该是分为不同的钩子去执行，或者是用户可选执行，区别：java类项目需要构建，而web前端则只需发布到Nginx等web服务器即可）

其他的疑问或者建议待本人多加实验后补充，目前先提那么多，作为备忘

**Comment by dreamans** [comment]
感谢 👍

**Comment by dreamans** [comment]
2.0已经支持，docs: https://rsy.me/syncd
