### ISSUE TITLE
tar (child): /tmp/.syncd/tmp/syncd_1_1.tar.gz：无法 open: 没有那个文件或目录

### ISSUE THREAD

**Issue by liyunde** [dreamans/syncd#49]
使用版本Syncd-v1.1.2-linux-amd64
系统CENTOS7.4
git version 2.21.0
syncd@localhost:~$ 上线失败
Error Output >>>
task run failed, exit status 141
tar (child): /tmp/.syncd/tmp/syncd_1_1.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
>>> 更新代码仓库文件 
完成
>>> 拉取代码文件 
完成
>>> 打包 
失败
task run failed, exit status 141
tar (child): /tmp/.syncd/tmp/syncd_1_1.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now

**Comment by dreamans** [comment]
有可能是权限问题，无法创建tar包，修改下workspace目录配置

**Comment by liyunde** [comment]
1. /tmp/.syncd 目录下有 1,2,3这样地目录,没有 tmp 权限给到777都不行
2. workspace 在哪里面配置
谢谢

**Comment by dreamans** [comment]
workspace在你启动时 -c 指定的配置文件里
