### ISSUE TITLE
发布-提交上线申请无法获取项目空间

### ISSUE THREAD

**Issue by imyzt** [dreamans/syncd#50]
syncd版本: 1.1.2  
系统版本: Linux version 4.4.0-17134-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #523-Microsoft Mon Dec 31 17:49:00 PST 2018  
other: `git version 2.18.0`,  `go-latest`, `mysql8`

问题: 已经配置了两个项目空间, 分别配置了两个项目, 日志信息配置输出控制台, 控制台没有看到错误信息, 但是在提交上线申请时无法获取项目空间. 是我配置或者是使用上还有问题吗? 

图-无法获取项目
![image](https://user-images.githubusercontent.com/28680198/54111557-1cd66b80-441f-11e9-944b-13ed01947b0d.png)

图-已配置的项目空间
![image](https://user-images.githubusercontent.com/28680198/54111850-d0d7f680-441f-11e9-9d4f-3261bba6ebb1.png)

图-已配置项目空间所属的项目
![image](https://user-images.githubusercontent.com/28680198/54111884-e77e4d80-441f-11e9-91ef-b7e85c25cd13.png)

图-syncd运行图
![image](https://user-images.githubusercontent.com/28680198/54112041-45129a00-4420-11e9-8c95-ee7aa5578ec7.png)

**Comment by dreamans** [comment]
还差一步操作：
将需要提交上线申请的用户加入到项目空间中，项目空间 -> 成员管理 -> 添加成员

**Comment by imyzt** [comment]
谢谢作者, 上面那个问题是解决了  

不过部署一个最简单的helloworld项目, 始终无法访问到目标主机，已经配置了ssh免密登录，并且把日志里面报连接超时的命令单独复制出来，每一个命令都能够成功运行，不是很清楚是怎么回事。  
单独做集群检测也是报错连接不上目标主机.

[日志文件](https://f.coka.la/SjDZQP.log)

图-集群检测
![image](https://user-images.githubusercontent.com/28680198/54182397-60db7600-44dc-11e9-99cd-481fee0cb330.png)

图-命令拆解到syncd运行的主机单独运行
![image](https://user-images.githubusercontent.com/28680198/54182411-689b1a80-44dc-11e9-9da6-2dcce97abc9c.png)

**Comment by imyzt** [comment]
问题已解决  

原因: 配置免密登录的密钥使用的普通用户, 启动syncd时使用的超级用户, 故syncd没有目标主机的免密执行权限.   
解决方法: 使用普通用户运行syncd或者为超级用户也配置目标机器的免密登录.
