### ISSUE TITLE
fatal: unknown date format format:%Y-%m-%d %H:%M:%S

### ISSUE THREAD

**Issue by wujunze** [dreamans/syncd#51]
fatal: unknown date format format:%Y-%m-%d %H:%M:%S

![image](https://user-images.githubusercontent.com/12997869/54471236-ba9bb300-47f0-11e9-81f1-be26ea66f454.png)

Thanks

**Comment by dreamans** [comment]
升级git到最新版本即可解决 .

**Comment by wujunze** [comment]
Thanks
