### ISSUE TITLE
找不到sql文件

### ISSUE THREAD

**Issue by liujunhu5122** [dreamans/syncd#61]
[root@centos7-205 syncd]# /bin/bash script/install_sql.sh 
script/install_sql.sh:行9: ./sql/syncd_v2.sql: 没有那个文件或目录

**Comment by dreamans** [comment]
文档已更新：https://syncd.cc/docs/#/install?id=%E5%AF%BC%E5%85%A5%E6%95%B0%E6%8D%AE%E5%BA%93
