### ISSUE TITLE
后台问题建议

### ISSUE THREAD

**Issue by liujunhu5122** [dreamans/syncd#63]
1、头像设置有问题
2、右上角个人设置修改不了用户名
3、不能守护进程

**Comment by dreamans** [comment]
1. 头像依赖gravatar.com，需要gravatar和syncd的用户邮箱一致才生效
2. 用户名不支持随便修改，需要有“编辑用户信息”权限的用户在用户管理中修改
3. 守护进程自己可实现，`2.1`版本会支持平滑启停
