### ISSUE TITLE
发布部署配置错误[cmd] $ echo 'packfile empty' && exit 1 

### ISSUE THREAD

**Issue by EricBatty** [dreamans/syncd#67]
请问作者有没有部署的案例，我在deploy的时候出现[cmd] $ echo 'packfile empty' && exit 1 错误
在项目管理的deploy_setting 里面只能设置整个集群吗？不能指定单个机器？user栏是不是填写的ssh主机的用户名？

**Comment by dreamans** [comment]
- [cmd] $ echo 'packfile empty' && exit 1 错误
参考：https://syncd.cc/docs/#/troubleuse?id=%E9%83%A8%E7%BD%B2%E5%A4%B1%E8%B4%A5%EF%BC%9Acmd-echo-39packfile-empty39-ampamp-exit-1-x
- deploy_setting 里面只能设置整个集群吗？
目前是的，2.1会支持机器维度的灰度部署
- user栏是不是填写的ssh主机的用户名？
是的

**Comment by showfilv** [comment]
我解决了。构建命令必须填，否则就会出这个错误。
