### ISSUE TITLE
最新版本没有二进制版吗，自己编译报错了~

### ISSUE THREAD

**Issue by lizeyun** [dreamans/syncd#68]
![image](https://user-images.githubusercontent.com/19726385/55453988-b1904b80-5610-11e9-907b-dee60a934022.png)

**Comment by sarices** [comment]
被墙了，还是提供二进制包比较方便部署

**Comment by siep1221** [comment]
直接用官网提供的安装脚本会有这个问题，手动去github下载最新版本的源码包，并且手动下载golang的sys.git，然后make就可以了

**Comment by dreamans** [comment]
用这个试试，解决被墙问题  http://goproxy.io/
