### ISSUE TITLE
前端代码调试相关

### ISSUE THREAD

**Issue by morya** [dreamans/syncd#72]
前端不太熟悉，照着 web 目录下的readme安装了yarn和npm依赖库，
使用`yarn run serve`启动，然后访问 `http://127.0.0.1:8080` 的npm调试页面，浏览器展示空白页。
但是看chrome调试工具，打开network里，是能看到读取到 app.js 等文件资源的。
找前端同事问过，他建议把 vue.config.js 的 publicPath 配置成 `/` 就ok了。
```js
{
    publicPath: '/static/',  // old value
    publicPath: '/',  // new value
```

可问题是，如果配置成 `/` 这个路径，打包的 `/web/dist` 中的静态文件，和 `syncd` 又没法一起工作。

**Comment by dreamans** [comment]
这个近期会进行优化的
