### ISSUE TITLE
安装syncd问题

### ISSUE THREAD

**Issue by sylarzeng** [dreamans/syncd#73]
curl https://syncd.cc/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   794  100   794    0     0    666      0  0:00:01  0:00:01 --:--:--   667
Cloning into '/root/.syncd-repo'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 3705 (delta 36), reused 108 (delta 36), pack-reused 3588
Receiving objects: 100% (3705/3705), 12.86 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (1509/1509), done.
Checking connectivity... done.
clean start >>>
rm -fr ./output
rm -f syncd_bin
>>> clean complete
build syncd start >>>
GOPROXY=https://goproxy.io go mod tidy
go build -o syncd_bin ./syncd/main.go
go: finding github.com/Unknwon/goconfig latest
go: finding gopkg.in/gomail.v2 latest
go: finding github.com/jinzhu/inflection latest
go: finding github.com/gin-contrib/sse latest
go: finding github.com/ugorji/go/codec latest
go: finding github.com/golang/protobuf/proto latest
go: downloading golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
../go/pkg/mod/github.com/mattn/go-isatty@v0.0.7/isatty_linux.go:7:8: unknown import path "golang.org/x/sys/unix": unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: connect: connection timed out)
make: *** [build] Error 1
cp: cannot stat ‘/root/.syncd-repo/output’: No such file or directory

Installing Syncd Path:  /root/syncd-deploy
Install complete.

**Comment by dreamans** [comment]
试试goproxy.io
