### ISSUE TITLE
怎么构建php代码，构建很慢而且构建完就删除了

### ISSUE THREAD

**Issue by mingyang313** [dreamans/syncd#78]

**Comment by dreamans** [comment]
参考文档：https://syncd.cc/docs/#/build?id=laravel%E6%9E%84%E5%BB%BA%E7%A4%BA%E4%BE%8B

**Comment by baogaitou** [comment]
保留一份 vendor, 构建时 cp 到 working directory, 目前 前端的 node_modules、PHP 的 vendor，go 依赖的自有库都是这么干的.
```shell
cd { working_directory }
cp -arp /data/tmp/vendor ./vendor
composer install
```
如果目录过大, 软链也可以.
我们还自建了composer 镜像和 npm registry 缓存服务器，编译安装时再次加速。
