### ISSUE TITLE
按照官方文档无法编译安装

### ISSUE THREAD

**Issue by fsygit** [dreamans/syncd#85]
使用安装命令：curl https://syncd.cc/install.sh | bash
报错：unrecognized import path "cloud.google.com/go"  (get https://cloud.google.com/go?go-get=1:dial tcp 172.217.27.142:443: i/o timeout)

**Comment by njutsiang** [comment]
![QQ截图20190429225807](https://user-images.githubusercontent.com/8214155/56905133-45e7b400-6ad2-11e9-8162-6975ae577258.png)
export http_proxy=socks5://127.0.0.1:1080
export https_proxy=socks5://127.0.0.1:1080
可以给 go get 开个代理

**Comment by dreamans** [comment]
可使用 goproxy.io
