### ISSUE TITLE
后台命令无法执行成功

### ISSUE THREAD

**Issue by yangruiyou85** [dreamans/syncd#87]
![image](https://user-images.githubusercontent.com/5554544/56951698-1a64d800-6b6b-11e9-8ad3-b8b518b56a3a.png)

版本v2.0.0

构建和部署都显示成功，但是/data/test/bin/syncd -c /data/test/etc/syncd.ini &  后台启动服务无法成功，该命令写在“部署后运行命令”中。
在本地执行/data/test/bin/syncd -c /data/test/etc/syncd.ini &    是可以正常启动syncd服务

**Comment by dreamans** [comment]
将输出重定向
