### ISSUE TITLE
语言包切换问题

### ISSUE THREAD

**Issue by baogaitou** [dreamans/syncd#92]
Hi , 安装 syncd 以后，发现语言包是英文的,很多词条都带下划线，部分区域是中文，请问是编译安装过程出问题了吗?  syncd-deploy 目录内没有发现语言和模板相关的文件，请指点:)

<img width="916" alt="Jietu20190605-162407@2x" src="https://user-images.githubusercontent.com/4033500/58941447-5fa1a880-87ae-11e9-9825-13dc7cab0051.png">

**Comment by dreamans** [comment]
把浏览器第一语言改成中文即可

**Comment by baogaitou** [comment]
> 把浏览器第一语言改成中文即可
...
