### ISSUE TITLE
RPC failed

### ISSUE THREAD

**Issue by jjason12138-jpg** [dreamans/syncd#98]
in /Users/xxxx/goworkspace/pkg/mod/cache/vcs/6310ae0a635ce9b4d0073713c68a8462977a85bc4f6c9d1fd99854a36fcab1f0: exit status 128:
	error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
	fatal: the remote end hung up unexpectedly
	fatal: early EOF
	fatal: index-pack failed

**Comment by dreamans** [comment]
本地openssl问题
